-- MySQL Script generated by MySQL Workbench
-- Sun Aug 29 18:18:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `username` VARCHAR(45) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL DEFAULT 0,
  `active` INT NOT NULL DEFAULT 0,
  `creationTime` DATETIME NOT NULL,
  `failedLogin` INT NOT NULL DEFAULT 0,
  `verificationHash` LONGTEXT NOT NULL,
  `banned` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Description` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `synopsis` LONGTEXT NOT NULL,
  `year` YEAR(4) NOT NULL,
  `image` LONGTEXT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `image_UNIQUE` (`image` ASC) ,
  UNIQUE INDEX `synopsis_UNIQUE` (`synopsis` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` INT NOT NULL,
  `media` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `description`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Movies_description1_idx` (`description` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  UNIQUE INDEX `description_UNIQUE` (`description` ASC) ,
  UNIQUE INDEX `media_UNIQUE` (`media` ASC) ,
  CONSTRAINT `fk_Movies_description1`
    FOREIGN KEY (`description`)
    REFERENCES `mydb`.`Description` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `genre_UNIQUE` (`genre` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shows` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `description`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Show_Description2_idx` (`description` ASC) ,
  UNIQUE INDEX `description_UNIQUE` (`description` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  CONSTRAINT `fk_Show_Description2`
    FOREIGN KEY (`description`)
    REFERENCES `mydb`.`Description` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seasons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `season` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `season_UNIQUE` (`season` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Season_show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Season_show` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `show` INT NOT NULL,
  `season` INT NOT NULL,
  PRIMARY KEY (`id`, `show`, `season`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Season_show_Show1_idx` (`show` ASC) ,
  INDEX `fk_Season_show_Season1_idx` (`season` ASC) ,
  CONSTRAINT `fk_Season_show_Show1`
    FOREIGN KEY (`show`)
    REFERENCES `mydb`.`Shows` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Season_show_Season1`
    FOREIGN KEY (`season`)
    REFERENCES `mydb`.`Seasons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Episodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Episodes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `media` LONGTEXT NOT NULL,
  `infos` INT NOT NULL,
  PRIMARY KEY (`id`, `infos`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Episode_Season_show1_idx` (`infos` ASC) ,
  UNIQUE INDEX `media_UNIQUE` (`media` ASC) ,
  UNIQUE INDEX `infos_UNIQUE` (`infos` ASC) ,
  CONSTRAINT `fk_Episode_Season_show1`
    FOREIGN KEY (`infos`)
    REFERENCES `mydb`.`Season_show` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genres_show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres_show` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `show` INT NOT NULL,
  `genre` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  PRIMARY KEY (`id`, `show`, `genre`),
  INDEX `fk_genres_show_Show1_idx` (`show` ASC) ,
  INDEX `fk_genres_show_Genres1_idx` (`genre` ASC) ,
  CONSTRAINT `fk_genres_show_Show1`
    FOREIGN KEY (`show`)
    REFERENCES `mydb`.`Shows` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genres_show_Genres1`
    FOREIGN KEY (`genre`)
    REFERENCES `mydb`.`Genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genres_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres_movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie` INT NOT NULL,
  `genre` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  PRIMARY KEY (`id`, `movie`, `genre`),
  INDEX `fk_genres_movie_Movies1_idx` (`movie` ASC) ,
  INDEX `fk_genres_movie_Genre1_idx` (`genre` ASC) ,
  CONSTRAINT `fk_genres_movie_Movies1`
    FOREIGN KEY (`movie`)
    REFERENCES `mydb`.`Movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genres_movie_Genre1`
    FOREIGN KEY (`genre`)
    REFERENCES `mydb`.`Genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `episode` INT NULL,
  `movie` INT NULL,
  PRIMARY KEY (`id`, `episode`, `movie`),
  INDEX `fk_Favorites_Episode1_idx` (`episode` ASC) ,
  INDEX `fk_Favorites_Movies1_idx` (`movie` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_Favorites_Episode1`
    FOREIGN KEY (`episode`)
    REFERENCES `mydb`.`Episodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorites_Movies1`
    FOREIGN KEY (`movie`)
    REFERENCES `mydb`.`Movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favorites_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favorites_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `favorite` INT NOT NULL,
  PRIMARY KEY (`id`, `user`, `favorite`),
  INDEX `fk_Favorites_user_Users1_idx` (`user` ASC) ,
  INDEX `fk_Favorites_user_Favorites1_idx` (`favorite` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `favorite_UNIQUE` (`favorite` ASC) ,
  CONSTRAINT `fk_Favorites_user_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`Users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorites_user_Favorites1`
    FOREIGN KEY (`favorite`)
    REFERENCES `mydb`.`Favorites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`History` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `episode` INT NULL,
  `movie` INT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`, `episode`, `movie`),
  INDEX `fk_History_Episode1_idx` (`episode` ASC) ,
  INDEX `fk_History_Movies1_idx` (`movie` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_History_Episode1`
    FOREIGN KEY (`episode`)
    REFERENCES `mydb`.`Episodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_History_Movies1`
    FOREIGN KEY (`movie`)
    REFERENCES `mydb`.`Movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`History_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`History_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `history` INT NOT NULL,
  PRIMARY KEY (`id`, `user`, `history`),
  INDEX `fk_History_user_Users1_idx` (`user` ASC) ,
  INDEX `fk_History_user_History1_idx` (`history` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `history_UNIQUE` (`history` ASC) ,
  CONSTRAINT `fk_History_user_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`Users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_History_user_History1`
    FOREIGN KEY (`history`)
    REFERENCES `mydb`.`History` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
